// Standard checklist of products/services for a new home-build project.
// Every new project starts with these, empty (no subcontractor bids yet) --
// click into one to request a bid from a subcontractor.
export const DEFAULT_PRODUCTS_SERVICES: string[] = [
  "Appliances",
  "Cabinets & hardware",
  "Central Vac",
  "Construction Doors",
  "Culverts",
  "Door Hardware",
  "Drywall Labor & Material",
  "Electrical",
  "Electrical Fixtures",
  "Engineering",
  "Excavation (including Culverts)",
  "Exterior & Interior Doors",
  "Exterior Masonry",
  "Exterior Paint",
  "Fencing",
  "Final Clean & Windows",
  "Financing Costs",
  "Finish Trim Labor",
  "Finish Trim Material",
  "Fireplace - Great Room",
  "Fireplace - Primary Bedroom",
  "Fireplace Mantle - Great Room",
  "Flatwork (Garage, Porch, Patio, Driveway)",
  "Floor Trusses",
  "Foundation/Footings",
  "Framing Labor",
  "Front Door",
  "Garage Doors",
  "Gutters",
  "HVAC",
  "Insulation",
  "Interior Doors",
  "Interior Masonry",
  "Interior Paint",
  "Landscaping",
  "Lot Cost",
  "Low Voltage",
  "Lumber",
  "Manual J",
  "Mirrors + Install",
  "Paint (Int. & Ext)",
  "Permits",
  "Plan Design",
  "Plumbing fixtures",
  "Plumbing Labor",
  "Plumbing Tubs, Toilets, Sinks",
  "Pool",
  "Power washing",
  "Realtor Fees",
  "Restroom",
  "Roof Trusses (included in lumber)",
  "Roofing",
  "Septic system",
  "Septic Permit",
  "Shower Doors",
  "Siding Labor & Material",
  "Siding Material",
  "Sport Court (floor and Hoop(s))",
  "Stairs, Railings, Newels",
  "Stucco",
  "Surfaces (flooring, countertops, tile)",
  "Towel Hangers, Toilet Paper Holders, Etc.",
  "Trash Box",
  "Wainscoting, Paneling",
  "Window Cleaning",
  "Window Tint / Smart Tint",
  "Windows & Sliding Doors",
];
